// #include "../minishell.h"


// // char *sub_quotes(char *line, int start)
// // {
// //     int i = start + 1;
// //     char quote = line[start];

// //     while (line[i] && line[i] != quote)
// //         i++;
// //     if (line[i] == quote)
// //         return ft_substr(line, start, i - start + 1);
// //     return NULL; 
// // }

// // int	quotes_handler(char *input, int start)
// // {
// // 	int i;

// // 	i = start + 1;

// // 	while (input[i])
// // 	{
// // 		if (input[i] == input[start])
// // 			return (i);
// // 		i++;
// // 	}
// // 	return (-1);
// // }


// // char **realloc_append(char **array, char *new_token) 
// // {
// //     int len = array_length(array);
// //     char **new_array = realloc(array, sizeof(char *) * (len + 2));
// //     if (!new_array) 
// //     {
// //         return NULL;
// //     }
// //     new_array[len] = ft_strdup(new_token); 
// //     new_array[len + 1] = NULL;
// //     return new_array;
// // }
// int array_length(char **array) 
// {
//     int len = 0;
//     while (array[len])
//         len++;
//     return len;
// }

// int is_token(char c)
// {
//     if (c == '|' || c == '<' || c == '>')
//         return 1;
//     return 0;
// }

// int	quotes_handler(char *input, int start, char c)
// {
// 	int i;

// 	i = start + 1;

// 	while (input[i])
// 	{
// 		if (input[i] == c)
// 			return (i + 1);
// 		i++;
// 	}
// 	return (0);
// }


// int find_token_pos(char *line, int *token_pos)
// {
//     int i ;
//     i = token_pos[1] + 1;

//     while (line[i] && line[i] == ' ')
//         i++;
//     token_pos[0] = i;
//     if (is_token(line[i]))
//     {
//         // if((line[i] == '>' && line[i + 1] == '>') || (line[i] == '<' && line[i + 1] == '<'))
//         // {
//         //     token_pos[1] = i + 1;
//         //     return (1);
//         // }
//         token_pos[1] = i + 1;
//         return (1);
//     }
//     if (line[i] == '\'' || line[i] == '\"')
//     {
//         token_pos[1] = quotes_handler(line, i, line[i]);
//         return (1);
//     }
//     while (line[i] &&(line[i] != ' ' && !is_token(line[i + 1])))
//             i++;
//     token_pos[1] = i;
//     return (0);
// }


// int lexer(t_command *data)
// {
//     int token_pos[2] = {-1, -1}; 
//     int ret_val;
//     char *new_token;
//     int i = 0;
//     int quote_end;

//     t_tokens    *new_token_struct;
//     // data = (t_command*) malloc(sizeof(t_command));
//     // data->args = (char **) malloc(sizeof(char *));
//     // if (!data->args)
//     //     return (0);
//     // data->args[0] = NULL;
//     while (1)
//     {
//         ret_val = find_token_pos(data->cmnd, token_pos);
//         new_token = ft_substr(data->cmnd, token_pos[0], token_pos[1] - token_pos[0]);
//         new_token_struct = ft_lstneww(new_token, 0);
//         ft_lstadd_backk(&(data->tokens_list), new_token_struct);
//         // data->args = realloc_append(data->args, new_token);
//         if (token_pos[1] >= ft_strlen(data->cmnd))
//             break;
//         free(new_token);
//         // free(new_token_struct);
//     }
//     return (1);
// }


// // int main()
// // {
// //     t_command *cmd;
// //     cmd = (t_command*)malloc(sizeof(t_command));

// //     char *input_str = "echo \"hl\"llo\"olll'l'o\"| |  u\"iu, < 'hello world'    '|'  grep 'hello' & > eoutput.txt";
// //     cmd->cmnd = input_str;
// //     // cmd->args = NULL; 
// //     lexer(cmd);
// //     printf("Tokens generated by the lexer: %s\n", input_str);
// //     while (cmd->tokens_list)
// //     {
// //         printf("%s\n",cmd->tokens_list->value);
// //         cmd->tokens_list = cmd->tokens_list->next;
// //     }
// //     // free(cmd->args);
// //     return 0;
// // }
// int main()
// {
//     t_command cmd; 
//     int i =0;
//     cmd.tokens_list = NULL; 
//     char *input_str = "echo o\"hl\"llo\"olll'l'o\"| |  u\"iu, < 'hello world'    '|'  grep 'hello' & > eoutput.txt";
//     cmd.cmnd = input_str;
//     lexer(&cmd); 
//     t_tokens *current = cmd.tokens_list;
//     printf("Tokens generated by the lexer: %s\n", input_str);
//     while (current)
//     {
//         printf("tokens[%d] : %s\n", i, current->value);
//         current = current->next;
//         i++;
//     }
//     return 0;
// }

int main()
{
	
}
